title 	Arch Linux
linux	/vmlinuz-linux
initrd 	/initramfs-linux.img
# Resorting to module_blacklist nouveau here, since blacklisting it in
# /etc/modprobe.d doesn't get rid of it.  Tried removing `kms` hook and putting
# `modconf` before anything else, still the module loads.  `mkinitcpio -v`
# properly shows that the blacklist file is found. Nvidia-utils also tries to
# blacklist the module but doesn't succeed
options rd.luks.name=299d4664-e48e-4d30-b1a9-2898b11844f9=root root=/dev/mapper/root rw
options nvidia-drm.fbdev=1
options nvidia-drm.modeset=1
options module_blacklist=nouveau
